"use client";

import { PageShell } from "@/components/page-shell";
import { StarField } from "@/components/zodiac-icons";
import { AlertTriangle, ShieldAlert, Stethoscope, Scale } from "lucide-react";

const disclaimers = [
  {
    icon: AlertTriangle,
    title: "Not Professional Advice",
    text: "Our palm reading and astrology predictions are not a substitute for professional medical, legal, financial, or psychological advice. Always consult qualified professionals for important life decisions related to health, finances, legal matters, or mental well-being. HastRekhaAI should not be relied upon as your sole source of guidance.",
  },
  {
    icon: ShieldAlert,
    title: "AI-Generated Content",
    text: "Our predictions are generated by artificial intelligence algorithms that combine traditional palmistry and astrological principles with modern technology. While we strive for meaningful and insightful readings, the accuracy of AI-generated content cannot be guaranteed. AI interpretations may vary from traditional expert readings.",
  },
];

const detailedTerms = [
  {
    icon: AlertTriangle,
    title: "Accuracy of Predictions",
    content: "HastRekhaAI makes no warranties or representations regarding the accuracy, reliability, or completeness of any prediction or reading provided through our platform. Astrological and palmistry readings are based on traditional interpretive frameworks and should be understood within that context. Results may vary based on image quality and input accuracy.",
  },
  {
    icon: Stethoscope,
    title: "Health & Medical Disclaimers",
    content: "Any references to health predictions, life span estimates, or medical conditions are derived from traditional palmistry interpretations and are purely symbolic in nature. They do not constitute medical diagnoses or prognoses and should never be used to make health-related decisions. Always consult healthcare professionals for medical concerns.",
  },
  {
    icon: Scale,
    title: "User Responsibility & Liability",
    content: "By using HastRekhaAI, you acknowledge that you are solely responsible for any decisions or actions taken based on the predictions and readings provided. We encourage users to approach all readings with an open mind while exercising personal judgment and critical thinking. HastRekhaAI shall not be liable for any damages arising from use of our services.",
  },
  {
    icon: AlertTriangle,
    title: "Cultural and Spiritual Context",
    content: "Our services draw from the rich traditions of Indian palmistry (Hastrekha Vigyan) and Vedic astrology (Jyotish Shastra). These are ancient spiritual and cultural practices that many people find valuable for personal insight and reflection. We respect these traditions and present our AI-enhanced interpretations with reverence for their origins.",
  },
];

export default function DisclaimerPage() {
  return (
    <PageShell>
      {/* Hero */}
      <section className="relative overflow-hidden py-16 lg:py-24">
        <StarField className="absolute inset-0" />
        <div className="relative mx-auto max-w-4xl px-4 text-center lg:px-8">
          <h1 className="font-serif text-4xl font-bold text-foreground md:text-5xl text-balance">
            Disclaimer
          </h1>
          <p className="mt-4 text-lg leading-relaxed text-muted-foreground">
            Please read this disclaimer carefully before using our palm reading and astrology prediction services. Understanding these important limitations helps you use our platform responsibly.
          </p>
          <p className="mt-2 text-sm text-muted-foreground">
            Last updated: May 2026 | Effective immediately
          </p>
        </div>
      </section>

      {/* Key Disclaimers */}
      <section className="py-16 lg:py-20">
        <div className="mx-auto max-w-4xl px-4 lg:px-8">
          <h2 className="mb-8 font-serif text-2xl font-bold text-foreground md:text-3xl text-center">
            Critical Disclaimers
          </h2>
          <div className="flex flex-col gap-6">
            {disclaimers.map((item) => {
              const Icon = item.icon;
              return (
                <article
                  key={item.title}
                  className="rounded-xl border border-primary/30 bg-primary/5 p-6"
                >
                  <div className="mb-3 flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-red-100 dark:bg-red-900/30 text-red-600 dark:text-red-400">
                      <Icon className="h-5 w-5" />
                    </div>
                    <h2 className="font-serif text-lg font-bold text-foreground">
                      {item.title}
                    </h2>
                  </div>
                  <p className="text-sm leading-relaxed text-muted-foreground">
                    {item.text}
                  </p>
                </article>
              );
            })}
          </div>
        </div>
      </section>

      {/* Detailed Terms */}
      <section className="bg-card/50 py-16 lg:py-20">
        <div className="mx-auto max-w-4xl px-4 lg:px-8">
          <h2 className="mb-8 font-serif text-2xl font-bold text-foreground md:text-3xl">
            Detailed Disclaimers & Limitations
          </h2>
          <div className="grid gap-6 md:grid-cols-2">
            {detailedTerms.map((item) => {
              const Icon = item.icon;
              return (
                <article
                  key={item.title}
                  className="rounded-xl border border-border/50 bg-card p-6"
                >
                  <div className="mb-3 flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
                      <Icon className="h-5 w-5" />
                    </div>
                    <h3 className="font-serif text-lg font-bold text-foreground">
                      {item.title}
                    </h3>
                  </div>
                  <p className="text-sm leading-relaxed text-muted-foreground">
                    {item.content}
                  </p>
                </article>
              );
            })}
          </div>
        </div>
      </section>

      {/* Important Information */}
      <section className="py-16 lg:py-20">
        <div className="mx-auto max-w-4xl px-4 lg:px-8">
          <h2 className="mb-8 font-serif text-2xl font-bold text-foreground md:text-3xl">
            Important Information
          </h2>
          <div className="flex flex-col gap-6 text-sm leading-relaxed text-muted-foreground">
            <div className="rounded-xl border border-border/50 bg-card p-6">
              <h3 className="mb-3 font-semibold text-foreground">Entertainment Purpose</h3>
              <p>
                HastRekhaAI readings are intended for entertainment, self-reflection, and spiritual guidance purposes only. While we incorporate traditional wisdom from centuries-old practices, our AI-powered interpretations should not be used as a basis for major life decisions without consulting appropriate professionals.
              </p>
            </div>
            <div className="rounded-xl border border-border/50 bg-card p-6">
              <h3 className="mb-3 font-semibold text-foreground">Image Quality Disclaimer</h3>
              <p>
                The accuracy of palm readings depends on the quality of the uploaded palm image. Poor lighting, image resolution, or angles may affect the analysis. We recommend uploading clear, well-lit images taken from multiple angles for best results. No guarantee can be made about prediction accuracy based on image quality alone.
              </p>
            </div>
            <div className="rounded-xl border border-border/50 bg-card p-6">
              <h3 className="mb-3 font-semibold text-foreground">No Warranty</h3>
              <p>
                HastRekhaAI is provided on an &quot;as-is&quot; basis. We make no warranties, express or implied, regarding the service&apos;s fitness for a particular purpose, merchantability, or non-infringement. Your use of our service is entirely at your own risk and discretion.
              </p>
            </div>
            <div className="rounded-xl border border-border/50 bg-card p-6">
              <h3 className="mb-3 font-semibold text-foreground">Limitation of Liability</h3>
              <p>
                HastRekhaAI and its creators shall not be held liable for any direct, indirect, incidental, special, or consequential damages arising from the use of our services, including but not limited to emotional distress, financial loss, loss of data, or decisions made based on our predictions. This applies even if we have been advised of the possibility of such damages.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Acceptance */}
      <section className="py-16 lg:py-20">
        <div className="mx-auto max-w-3xl px-4 text-center lg:px-8">
          <div className="rounded-xl border border-primary/20 bg-primary/5 p-8">
            <h2 className="mb-3 font-serif text-2xl font-bold text-foreground">
              Acknowledgment & Acceptance
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
              By accessing and using HastRekhaAI, you acknowledge that you have read, understood, and agree to this disclaimer in its entirety. You understand that all predictions are for entertainment and spiritual guidance purposes. You accept full responsibility for how you choose to interpret and act upon the information provided through our platform.
            </p>
          </div>
        </div>
      </section>
    </PageShell>
  );
}
