"use client";

import { PageShell } from "@/components/page-shell";
import { StarField } from "@/components/zodiac-icons";
import { AlertTriangle, Info, ShieldAlert } from "lucide-react";

const disclaimers = [
  {
    icon: AlertTriangle,
    title: "Not Professional Advice",
    text: "Our palm reading and astrology predictions are not a substitute for professional medical, legal, financial, or psychological advice. Always consult qualified professionals for important life decisions related to health, finances, legal matters, or mental well-being.",
  },
  {
    icon: ShieldAlert,
    title: "AI-Generated Content",
    text: "Our predictions are generated by artificial intelligence algorithms that combine traditional palmistry and astrological principles with modern technology. While we strive for meaningful and insightful readings, the accuracy of AI-generated content cannot be guaranteed.",
  },
];

export default function DisclaimerPage() {
  return (
    <PageShell>
      {/* Hero */}
      <section className="relative overflow-hidden py-16 lg:py-24">
        <StarField className="absolute inset-0" />
        <div className="relative mx-auto max-w-4xl px-4 text-center lg:px-8">
          <h1 className="font-serif text-4xl font-bold text-foreground md:text-5xl text-balance">
            Disclaimer
          </h1>
          <p className="mt-4 text-lg leading-relaxed text-muted-foreground">
            Please read this disclaimer carefully before using our palm reading
            and astrology prediction services.
          </p>
        </div>
      </section>

      {/* Key Disclaimers */}
      <section className="py-16 lg:py-20">
        <div className="mx-auto max-w-4xl px-4 lg:px-8">
          <div className="flex flex-col gap-6">
            {disclaimers.map((item) => {
              const Icon = item.icon;
              return (
                <div
                  key={item.title}
                  className="rounded-xl border border-border/50 bg-card p-6 transition-all hover:border-primary/30"
                >
                  <div className="mb-3 flex items-center gap-3">
                    <div className="flex h-10 w-10 items-center justify-center rounded-lg bg-primary/10 text-primary">
                      <Icon className="h-5 w-5" />
                    </div>
                    <h2 className="font-serif text-lg font-bold text-foreground">
                      {item.title}
                    </h2>
                  </div>
                  <p className="text-sm leading-relaxed text-muted-foreground">
                    {item.text}
                  </p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* Detailed Terms */}
      <section className="bg-card/50 py-16 lg:py-20">
        <div className="mx-auto max-w-3xl px-4 lg:px-8">
          <h2 className="mb-6 font-serif text-2xl font-bold text-foreground md:text-3xl">
            Detailed Terms
          </h2>
          <div className="flex flex-col gap-6 text-sm leading-relaxed text-muted-foreground">
            <div>
              <h3 className="mb-2 font-semibold text-foreground">Accuracy of Predictions</h3>
              <p>
                HastRekhaAI makes no warranties or representations regarding the accuracy,
                reliability, or completeness of any prediction or reading provided through
                our platform. Astrological and palmistry readings are based on traditional
                interpretive frameworks and should be understood within that context.
              </p>
            </div>
            <div>
              <h3 className="mb-2 font-semibold text-foreground">Life Span Predictions</h3>
              <p>
                Any references to estimated life span or health predictions are derived from
                traditional palmistry interpretations and are purely symbolic in nature. They
                do not constitute medical diagnoses or prognoses and should never be used to
                make health-related decisions.
              </p>
            </div>
            <div>
              <h3 className="mb-2 font-semibold text-foreground">User Responsibility</h3>
              <p>
                By using JyotishAI, you acknowledge that you are solely responsible for any
                decisions or actions taken based on the predictions and readings provided. We
                encourage users to approach all readings with an open mind while exercising
                personal judgment and critical thinking.
              </p>
            </div>
            <div>
              <h3 className="mb-2 font-semibold text-foreground">Cultural and Spiritual Context</h3>
              <p>
                Our services draw from the rich traditions of Indian palmistry (Hastrekha
                Vigyan) and Vedic astrology (Jyotish Shastra). These are ancient spiritual
                and cultural practices that many people find valuable for personal insight
                and reflection. We respect these traditions and present our AI-enhanced
                interpretations with reverence for their origins.
              </p>
            </div>
            <div>
              <h3 className="mb-2 font-semibold text-foreground">Limitation of Liability</h3>
              <p>
                HastRekhaAI and its creators shall not be held liable for any direct, indirect,
                incidental, or consequential damages arising from the use of our services,
                including but not limited to emotional distress, financial loss, or decisions
                made based on our predictions.
              </p>
            </div>
          </div>
        </div>
      </section>

      {/* Acceptance */}
      <section className="py-16 lg:py-20">
        <div className="mx-auto max-w-3xl px-4 text-center lg:px-8">
          <div className="rounded-xl border border-primary/20 bg-primary/5 p-8">
            <h2 className="font-serif text-xl font-bold text-foreground">
              By Using Our Services
            </h2>
            <p className="mt-3 text-sm leading-relaxed text-muted-foreground">
              By accessing and using HastRekhaAI, you acknowledge that you have read,
              understood, and agree to this disclaimer. You understand that all
              predictions are for entertainment and spiritual guidance purposes, and
              you accept full responsibility for how you choose to interpret and act
              upon the information provided.
            </p>
          </div>
        </div>
      </section>
    </PageShell>
  );
}
